"""What the representation schema guarantees: vectors are per-generation, the
lexical column is derived by the database, and both die with their chunk.
"""

import uuid

import pytest
from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError

from astrag.models import ActiveGenerationPointer, Chunk, ChunkRepresentation
from astrag.models.representation import DIMENSIONS
from astrag.settings import get_settings
from test_chunk_schema import make_chunk
from test_lifecycle_schema import make_corpus, make_document, make_version


@pytest.fixture
def chunk(db):
    return make_chunk(db, make_version(db, make_document(db, make_corpus(db))))


def make_representation(db, chunk, generation_id=None, **kwargs):
    pointer = db.scalars(select(ActiveGenerationPointer)).one()
    representation = ChunkRepresentation(
        chunk_id=chunk.id,
        search_representation_generation_id=(
            generation_id or pointer.search_representation_generation_id
        ),
        embedding=kwargs.pop("embedding", [0.1] * DIMENSIONS),
        model="text-embedding-3-small",
        input_tokens=9,
        **kwargs,
    )
    db.add(representation)
    db.flush()
    return representation


def test_the_configured_dimension_matches_the_column(db):
    """A mismatch would only surface as a failed insert on the first upload."""
    assert get_settings().embedding_dimensions == DIMENSIONS


def test_a_vector_of_the_wrong_width_is_rejected(db, chunk):
    with pytest.raises(Exception, match="expected 1536 dimensions"):
        make_representation(db, chunk, embedding=[0.1] * 8)


def test_one_vector_per_chunk_per_generation(db, chunk):
    """A retried embedding batch updates its row instead of adding a rival."""
    make_representation(db, chunk)

    with pytest.raises(IntegrityError, match="uq_chunk_representations_chunk_generation"):
        make_representation(db, chunk)


def test_an_unknown_generation_is_rejected(db, chunk):
    with pytest.raises(IntegrityError, match="search_representation_generation_id"):
        make_representation(db, chunk, generation_id=uuid.uuid4())


def test_the_lexical_column_is_derived_from_the_contextualized_text(db, chunk):
    """§15: generated by the database, so it cannot drift from its source."""
    lexical = db.scalar(select(Chunk.lexical).where(Chunk.id == chunk.id))

    assert "republ" in lexical  # stemmed by the english configuration
    assert db.scalar(
        select(func.count())
        .select_from(Chunk)
        .where(Chunk.id == chunk.id, Chunk.lexical.op("@@")(func.plainto_tsquery("english", "founded")))
    ) == 1


def test_dropping_the_chunk_drops_its_representation(db, chunk):
    representation = make_representation(db, chunk)

    db.delete(chunk)
    db.flush()

    assert db.scalars(
        select(ChunkRepresentation).where(ChunkRepresentation.id == representation.id)
    ).all() == []
