"""lifecycle schema

Revision ID: a9a1f4acd2c6
Revises: 
Create Date: 2026-08-17 15:34:40.273969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e20e1605703'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Generation rows are inserted by migrations; there is no generation-creation
# API. Literal ids so the seeded pointers are reproducible on every database.
PROCESSING_GENERATION_ID = '11111111-1111-1111-1111-111111111111'
SEARCH_REPRESENTATION_GENERATION_ID = '22222222-2222-2222-2222-222222222222'


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpora',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('processing_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_representation_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_generation_pointer',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('processing_generation_id', sa.UUID(), nullable=False),
    sa.Column('search_representation_generation_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_active_generation_pointer_single_row'),
    sa.ForeignKeyConstraint(['processing_generation_id'], ['processing_generations.id'], ),
    sa.ForeignKeyConstraint(['search_representation_generation_id'], ['search_representation_generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corpus_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'corpus_id', name='uq_documents_id_corpus_id')
    )
    op.create_index(op.f('ix_documents_corpus_id'), 'documents', ['corpus_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('corpus_id', sa.UUID(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_artifact_key', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'READY', 'READY_DEGRADED', 'FAILED', name='document_version_status'), server_default='PENDING', nullable=False),
    sa.Column('degraded_capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('published_processing_generation_id', sa.UUID(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id', 'corpus_id'], ['documents.id', 'documents.corpus_id'], name='fk_document_versions_document_corpus', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_processing_generation_id'], ['processing_generations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corpus_id', 'source_hash', name='uq_document_versions_corpus_source_hash')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index('uq_document_versions_one_in_flight', 'document_versions', ['document_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"))
    # ### end Alembic commands ###

    # ponytail: the SRG config names the openai embedding space. The offline fake
    # embedder is a different space and gets its own SRG row in rung 9 if it
    # needs one; deciding that here would be guessing ahead of the embedder.
    op.execute(
        f"""
        INSERT INTO processing_generations (id, config) VALUES (
            '{PROCESSING_GENERATION_ID}',
            '{{"parser": "v1", "normalizer": "v1",
                "chunker": "structure-aware-token-bounded-v1",
                "target_tokens": 512, "max_tokens": 800, "overlap_tokens": 64,
                "tokenizer": "cl100k_base"}}'::jsonb
        );
        INSERT INTO search_representation_generations (id, config) VALUES (
            '{SEARCH_REPRESENTATION_GENERATION_ID}',
            '{{"provider": "openai", "model": "text-embedding-3-small",
                "dimensions": 1536, "tokenizer": "cl100k_base"}}'::jsonb
        );
        INSERT INTO active_generation_pointer
            (id, processing_generation_id, search_representation_generation_id)
        VALUES (1, '{PROCESSING_GENERATION_ID}',
                '{SEARCH_REPRESENTATION_GENERATION_ID}');
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_versions_one_in_flight', table_name='document_versions', postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"))
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_corpus_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('active_generation_pointer')
    op.drop_table('search_representation_generations')
    op.drop_table('processing_generations')
    op.drop_table('corpora')
    # ### end Alembic commands ###
    # Autogenerate does not drop the enum type it created.
    op.execute('DROP TYPE document_version_status')
