"""active version pointer on documents

Revision ID: 10bd9b50b522
Revises: ef77d396e539
Create Date: 2026-08-17 17:14:40.769436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bd9b50b522'
down_revision: Union[str, Sequence[str], None] = 'ef77d396e539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('active_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_versions', ['active_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'active_version_id')
    # ### end Alembic commands ###
