"""normalized artifact key on runs

Revision ID: 6ee2bbed5a75
Revises: b395f45d0f13
Create Date: 2026-08-17 16:39:21.961433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee2bbed5a75'
down_revision: Union[str, Sequence[str], None] = 'b395f45d0f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs', sa.Column('normalized_artifact_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_runs', 'normalized_artifact_key')
    # ### end Alembic commands ###
