"""chunks table

Revision ID: 75035eef0987
Revises: 6ee2bbed5a75
Create Date: 2026-08-17 16:43:58.889931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75035eef0987'
down_revision: Union[str, Sequence[str], None] = '6ee2bbed5a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The composite FK below references it, so it has to exist first.
    op.create_unique_constraint('uq_document_versions_id_document_id_corpus_id', 'document_versions', ['id', 'document_id', 'corpus_id'])
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corpus_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('processing_generation_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('contextualized_text', sa.Text(), nullable=False),
    sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id', 'document_id', 'corpus_id'], ['document_versions.id', 'document_versions.document_id', 'document_versions.corpus_id'], name='fk_chunks_version_document_corpus', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_generation_id'], ['processing_generations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'processing_generation_id', 'ordinal', name='uq_chunks_version_generation_ordinal')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_versions_id_document_id_corpus_id', 'document_versions', type_='unique')
    op.drop_table('chunks')
    # ### end Alembic commands ###
