"""temporal mentions

Revision ID: 9d26df2b7a51
Revises: 75035eef0987
Create Date: 2026-08-17 16:51:08.928708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d26df2b7a51'
down_revision: Union[str, Sequence[str], None] = '75035eef0987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporal_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('origin', sa.Enum('SOURCE_METADATA', 'CONTENT_MENTION', name='temporal_origin'), nullable=False),
    sa.Column('precision', sa.Enum('DAY', 'MONTH', 'YEAR', 'SEASON', 'DECADE', 'CENTURY', 'RANGE', 'UNKNOWN', name='temporal_precision'), nullable=False),
    sa.Column('certainty', sa.Enum('EXACT', 'APPROXIMATE', 'UNCERTAIN', name='temporal_certainty'), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('start_month', sa.Integer(), nullable=True),
    sa.Column('start_day', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'block_id', 'start_offset', 'end_offset', name='uq_temporal_mentions_chunk_span')
    )
    op.create_index(op.f('ix_temporal_mentions_chunk_id'), 'temporal_mentions', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporal_mentions_chunk_id'), table_name='temporal_mentions')
    op.drop_table('temporal_mentions')
    # ### end Alembic commands ###
