"""ingestion runs and jobs

Revision ID: b395f45d0f13
Revises: 0e20e1605703
Create Date: 2026-08-17 16:31:10.202823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b395f45d0f13'
down_revision: Union[str, Sequence[str], None] = '0e20e1605703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'CLAIMED', 'DONE', 'FAILED', name='ingestion_job_state'), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retry_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id')
    )
    op.create_index('ix_ingestion_jobs_claimable', 'ingestion_jobs', ['retry_after'], unique=False, postgresql_where=sa.text("state = 'PENDING'"))
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('processing_generation_id', sa.UUID(), nullable=False),
    sa.Column('search_representation_generation_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_stage', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_retryable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_generation_id'], ['processing_generations.id'], ),
    sa.ForeignKeyConstraint(['search_representation_generation_id'], ['search_representation_generations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'attempt', name='uq_ingestion_runs_version_attempt')
    )
    op.create_index(op.f('ix_ingestion_runs_document_version_id'), 'ingestion_runs', ['document_version_id'], unique=False)
    op.create_index('uq_ingestion_runs_one_active', 'ingestion_runs', ['document_version_id', 'processing_generation_id'], unique=True, postgresql_where=sa.text('finished_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ingestion_runs_one_active', table_name='ingestion_runs', postgresql_where=sa.text('finished_at IS NULL'))
    op.drop_index(op.f('ix_ingestion_runs_document_version_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_ingestion_jobs_claimable', table_name='ingestion_jobs', postgresql_where=sa.text("state = 'PENDING'"))
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
    # Dropping the table leaves the enum type behind, which makes re-upgrading fail.
    sa.Enum(name='ingestion_job_state').drop(op.get_bind())
