"""chunk representations and lexical column

Revision ID: ef77d396e539
Revises: 9d26df2b7a51
Create Date: 2026-08-17 17:03:14.479797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef77d396e539'
down_revision: Union[str, Sequence[str], None] = '9d26df2b7a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_representations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('search_representation_generation_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_representation_generation_id'], ['search_representation_generations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'search_representation_generation_id', name='uq_chunk_representations_chunk_generation')
    )
    op.create_index('ix_chunk_representations_embedding_hnsw', 'chunk_representations', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('chunks', sa.Column('lexical', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', contextualized_text)", persisted=True), nullable=False))
    op.create_index('ix_chunks_lexical', 'chunks', ['lexical'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_lexical', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'lexical')
    op.drop_index('ix_chunk_representations_embedding_hnsw', table_name='chunk_representations', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunk_representations')
    # ### end Alembic commands ###
